### ISSUE TITLE
cannot verify or add vendor in admin get a blank page

### ISSUE THREAD

**Issue by bobbrown1967** [syamvilakudy/Cart-Mart#33]
the error log I get is

2015-08-08T16:22:19+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Openwriter_Cartmart_Block_Adminhtml_Vendor_Edit_Tabs' in /home/xxxxxx/public_html/xxxxxxxx.com/app/Mage.php:595
Stack trace:
#0 /home/xxxxxx/public_html/xxxxxx.com/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /home/xxxxxx/public_html/xxxxxx.com/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('cartmart/adminh...', Array)
#2 /home/xxxxxx/public_html/xxxxxx.com/app/code/community/Openwriter/Cartmart/controllers/Adminhtml/VendorController.php(53): Mage_Core_Model_Layout->createBlock('cartmart/adminh...')
#3 /home/xxxxxx/public_html/xxxxxx.com/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Openwriter_Cartmart_Adminhtml_VendorController->editAction()
#4 /home/xxxxxx/public_html/xxxxxx.com/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#5 /home/xxxxxx/public_html/xxxxxx.com/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#6 /home/xxxxxx/public_html/xxxxxx.com/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#7 /home/xxxxxx/public_html/xxxxxx.com/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#8 /home/xxxxxx/public_html/xxxxxx.com/index.php(83): Mage::run('', 'store')
#9 {main}

**Comment by shazadmaved** [comment]
Did you get a solution for this?

**Comment by albertobraschi** [comment]
Hi; fresh install, magento CE, 1.9.2.3, when logged as vendor int the following pages: orders, transations, reviews. what can it be? 
maybe ACL?

https://gyazo.com/a75e38248d88c25c122b39ec2b3bf714

**Comment by rahulplague** [comment]
@albertobraschi 
Add this function in orders, transations, reviews controllers.
 protected function _isAllowed()
   {
       return true;
   }
